- name: Build Docker image
      community.docker.docker_image:
        name: tomcat_image
        tag: "1.0"
        build:
          path: /mnt
        source: build
        state: present

    - name: Create custom network
      community.docker.docker_network:
        name: deploy_net
        driver: bridge
        state: present
  
     - name: Copy Dockerfile
       copy:
         src: Dockerfile
         dest: /mnt/Dockerfile

      - name: Copy WAR file
        copy:
          src: sample.war
          dest: /mnt/sample.war


